### ISSUE TITLE
fatal error: 'QApplication' file not found

### ISSUE THREAD

**Issue by iBobik** [RfidResearchGroup/homebrew-proxmark3#21]
```
$ brew reinstall proxmark3
==> Downloading https://github.com/RfidResearchGroup/proxmark3/archive/v4.9237.tar.gz
Already downloaded: /Users/Bobik/Library/Caches/Homebrew/downloads/8d6348999984c4412e8cb081c1b3fa53b78eb10062c506ff1d8e16344dd22763--proxmark3-4.9237.tar.gz
==> Reinstalling rfidresearchgroup/proxmark3/proxmark3 
==> make clean
==> make all PLATFORM=PM3OTHER BREW_PREFIX=/usr/local
Last 15 lines from /Users/Bobik/Library/Logs/Homebrew/proxmark3/02.make:
[-] CC src/flash.c
[-] CC src/wiegand_formats.c
[-] CC src/wiegand_formatutils.c
[-] CC ../common/cardhelper.c
[-] CC src/preferences.c
[-] CC src/util_darwin.m
[-] UIC src/ui/ui_overlays.h
[-] CXX src/proxgui.cpp
In file included from src/proxgui.cpp:14:
src/proxguiqt.h:17:10: fatal error: 'QApplication' file not found
#include <QApplication>
         ^~~~~~~~~~~~~~
1 error generated.
make[1]: *** [obj/proxgui.o] Error 1
make: *** [client/all] Error 2

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/RfidResearchGroup/homebrew-proxmark3/issues
```

macOS Big Sur 11.2.2 (20D80)

**Comment by iceman1001** [comment]
Have you tried removing before?
```
brew remove proxmark3
brew reinstall proxmark3
``` 
The QT5 dependency is in the recipe

**Comment by iBobik** [comment]
Yes, tried:
```
$ brew remove proxmark3
Error: No available formula or cask with the name "proxmark3".
```

**Comment by iBobik** [comment]
Btw:
```
$ brew info QT5
qt@5: stable 5.15.2 (bottled) [keg-only]
Cross-platform application and UI framework
https://www.qt.io/
/usr/local/Cellar/qt@5/5.15.2 (10,688 files, 367.9MB)
  Poured from bottle on 2021-03-03 at 03:14:42
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/qt@5.rb
License: GFDL-1.3-only and GPL-2.0-only and GPL-3.0-only and LGPL-2.1-only and LGPL-3.0-only
==> Dependencies
Build: pkg-config ✔
==> Requirements
Build: Xcode ✔
Required: macOS >= 10.12 ✔
==> Caveats
We agreed to the Qt open source license for you.
If this is unacceptable you should uninstall.

qt@5 is keg-only, which means it was not symlinked into /usr/local,
because this is an alternate version of another formula.

If you need to have qt@5 first in your PATH, run:
  echo 'export PATH="/usr/local/opt/qt@5/bin:$PATH"' >> ~/.zshrc

For compilers to find qt@5 you may need to set:
  export LDFLAGS="-L/usr/local/opt/qt@5/lib"
  export CPPFLAGS="-I/usr/local/opt/qt@5/include"

For pkg-config to find qt@5 you may need to set:
  export PKG_CONFIG_PATH="/usr/local/opt/qt@5/lib/pkgconfig"

==> Analytics
install: 1,830 (30 days), 1,860 (90 days), 1,860 (365 days)
install-on-request: 168 (30 days), 198 (90 days), 198 (365 days)
build-error: 0 (30 days)
```

**Comment by mtebbens** [comment]
X2

 ~ % brew doctor
Your system is ready to brew.

 ~ % brew list
arm-none-eabi-gcc	gettext			qt			readline
astyle			pkg-config		qt@5			recode

 ~ % brew install --HEAD --with-blueshark proxmark3            
==> Installing proxmark3 from rfidresearchgroup/proxmark3
==> Cloning https://github.com/RfidResearchGroup/proxmark3.git
Updating /Users/xxxxxx/Library/Caches/Homebrew/proxmark3--git
==> Checking out branch master
Already on 'master'
Your branch is up to date with 'origin/master'.
HEAD is now at 39e7a58 default to oem 900 for C15001 format
==> make clean
==> make all PLATFORM=PM3RDV4 PLATFORM_EXTRAS=BTADDON BREW_PREFIX=/usr/local
Last 15 lines from /Users/xxxxxx/Library/Logs/Homebrew/proxmark3/02.make:
[-] CC ../common/iso15693tools.c
[-] CC ../common/legic_prng.c
[-] CC ../common/lfdemod.c
[-] CC ../common/parity.c
[-] CC ../common/util_posix.c
[-] CC src/pm3_luawrap.c
[-] UIC src/ui/ui_overlays.h
[-] CXX src/proxgui.cpp
In file included from src/proxgui.cpp:14:
src/proxguiqt.h:17:10: fatal error: 'QApplication' file not found
#include <QApplication>
         ^~~~~~~~~~~~~~
1 error generated.
make[1]: *** [obj/proxgui.o] Error 1
make: *** [client/all] Error 2

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/RfidResearchGroup/homebrew-proxmark3/issues

Please create pull requests instead of asking for help on Homebrew's GitHub,
Twitter or any other official channels.

On MBP Intel
Big Sur: Verison 11.2.1 (20D75)

**Comment by mtebbens** [comment]
Ok, qt JUST got updated.... Now it compiled and installed, no errors.
Although it installed a TON of dependencies:

Installing dependencies for qt: assimp, dbus, double-conversion, libpng, freetype, libffi, pcre, gdbm, mpdecimal, openssl@1.1, sqlite, tcl-tk, xz, python@3.9, glib, icu4c, jpeg, jasper, libb2, libproxy, libtiff, pcre2, webp and zstd

~ % brew update
Updated 1 tap (homebrew/core).
==> Updated Formulae
teleport

You have 1 outdated formula installed.
You can update it with brew upgrade.

~ % brew upgrade
==> Upgrading 1 outdated package:
qt 5.15.2 -> 6.0.1
==> Upgrading qt 5.15.2 -> 6.0.1
....

THEN:

brew install --HEAD --with-blueshark proxmark3
==> Installing proxmark3 from rfidresearchgroup/proxmark3
==> Cloning https://github.com/RfidResearchGroup/proxmark3.git
Updating /Users/xxxxxxx/Library/Caches/Homebrew/proxmark3--git
==> Checking out branch master
Already on 'master'
Your branch is up to date with 'origin/master'.
HEAD is now at 39e7a58 default to oem 900 for C15001 format
==> make clean
==> make all PLATFORM=PM3RDV4 PLATFORM_EXTRAS=BTADDON BREW_PREFIX=/usr/local
==> make install PREFIX=/usr/local/Cellar/proxmark3/HEAD-39e7a58 PLATFORM=PM3RDV4 PLATFORM_EXTRAS=BTADDON BREW_PREFIX=/usr/local
==> Install success!
==> The latest bootloader and firmware binaries are ready and waiting in the current homebrew Cellar within share/firmware.
🍺  /usr/local/Cellar/proxmark3/HEAD-39e7a58: 674 files, 41MB, built in 1 minute 24 seconds
Removing: /Users/xxxxxxx/Library/Caches/Homebrew/proxmark3--4.9237.tar.gz... (11.5MB)

~ % pm3
[=] Waiting for Proxmark3 to appear...

**Comment by iceman1001** [comment]
The pm3 client was tested to compile with QT4 and QT5,   so the new QT6 is quite untested...

**Comment by iBobik** [comment]
I've reinstalled qt (so upgraded to current v. 6) and installation of proxamrk3 was successful.
